curl -X POST http://localhost:5000/api/auth/register \
  -H "Content-Type: application/json" \
  -d '{
    "username": "johndoje",
    "email": "jhohn@example.com",
    "password": "123456",
    "role": "reader"
  }'

###
curl -X POST http://localhost:5000/api/auth/register \
  -H "Content-Type: application/json" \
  -d '{
    "username": "sim",
    "email": "sim@example.com",
    "password": "123456",
    "role": "author"
  }'

###
// Login request
  curl -X POST http://localhost:5000/api/auth/login \
  -H "Content-Type: application/json" \
  -d '{
    "email": "john@example.com",
    "password": "123456"
  }'

### Get All Users (Admin Only)
curl -X GET http://localhost:5000/api/users \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWE5NDU4OGIzMmRjYWZlNDM2YzRhNSIsImlhdCI6MTc0NjU3MjM3NiwiZXhwIjoxNzQ5MTY0Mzc2fQ.eJdwuwFuJ9y402Oc5tL1qjFa1oKMiLAp1tACbOfxtMA"

###  Get User by ID 
curl -X GET http://localhost:5000/api/users/681a94588b32dcafe436c4a5 \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWE4ZGYyMTVlMGVhYmJjYjFkZTAwOSIsImlhdCI6MTc0NjU3MjUwNywiZXhwIjoxNzQ5MTY0NTA3fQ.CQ05CK7dUGsTGUy91ZU6HbiSra6tA0DcSQqjR2HznaA"

### Update User (Self or Admin)
curl -X PUT http://localhost:5000/api/users/681a8df215e0eabbcb1de009 \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWE4ZGYyMTVlMGVhYmJjYjFkZTAwOSIsImlhdCI6MTc0NjU3MjUwNywiZXhwIjoxNzQ5MTY0NTA3fQ.CQ05CK7dUGsTGUy91ZU6HbiSra6tA0DcSQqjR2HznaA" \
-H "Content-Type: application/json" \
-d '{
  "username": "newussername",
  "email": "newemail@example.com",
  "role": "admin"
}'

###. Delete User (Admin Only)
curl -X DELETE http://localhost:5000/api/users/681a8df215e0eabbcb1de009 \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWE5NDU4OGIzMmRjYWZlNDM2YzRhNSIsImlhdCI6MTc0NjU3MjM3NiwiZXhwIjoxNzQ5MTY0Mzc2fQ.eJdwuwFuJ9y402Oc5tL1qjFa1oKMiLAp1tACbOfxtMA"

###  Ban User (Admin Only)
curl -X POST http://localhost:5000/api/users/ban/681a9a4c1527ddd4341650c5 \
-H "Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWE5NDU4OGIzMmRjYWZlNDM2YzRhNSIsImlhdCI6MTc0NjU3NDA4NCwiZXhwIjoxNzQ5MTY2MDg0fQ.MUC66Xv7_lQwvOHhxGsE9hJ1pKhmtfZFR_qgQTglpSs"

### Get All Posts
curl -X GET http://localhost:5000/api/posts \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWE5NDU4OGIzMmRjYWZlNDM2YzRhNSIsImlhdCI6MTc0NjU3MjM3NiwiZXhwIjoxNzQ5MTY0Mzc2fQ.eJdwuwFuJ9y402Oc5tL1qjFa1oKMiLAp1tACbOfxtMA"

### Get Post by ID
curl -X GET http://localhost:5000/api/posts/681ab6b8264258bc8a9ac9ed \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWE5NDU4OGIzMmRjYWZlNDM2YzRhNSIsImlhdCI6MTc0NjU3MjM3NiwiZXhwIjoxNzQ5MTY0Mzc2fQ.eJdwuwFuJ9y402Oc5tL1qjFa1oKMiLAp1tACbOfxtMA"

### Create Post 
curl -X POST http://localhost:5000/api/posts \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWMxMTJjNmVlNDhiMmE3NjFmYWZmMyIsImlhdCI6MTc0NjY2OTg2OCwiZXhwIjoxNzQ5MjYxODY4fQ.whbO1qxOTL8sWkNQ5TCUUv9CU9Xb-9jzyFdqNbC4szo" \
-F "title=Great Post" \
-F "content=This  blog post with an image." \
-F "tags=vue,php,blog" \
-F "image=@C:/Users/Simeon/OneDrive/Pictures/q.png"


### Update Post 
curl -X PUT http://localhost:5000/api/posts/681ac050cb81ba362038432e \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWE5NDU4OGIzMmRjYWZlNDM2YzRhNSIsImlhdCI6MTc0NjU3MjM3NiwiZXhwIjoxNzQ5MTY0Mzc2fQ.eJdwuwFuJ9y402Oc5tL1qjFa1oKMiLAp1tACbOfxtMA" \
-H "Content-Type: application/json" \
-d '{
  "title": "Updated Title",
  "content": "<p>Updated content here...</p>"
}'

### Delete Post
curl -X DELETE http://localhost:5000/api/posts/681ab6b8264258bc8a9ac9ed \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWE5NDU4OGIzMmRjYWZlNDM2YzRhNSIsImlhdCI6MTc0NjU3MjM3NiwiZXhwIjoxNzQ5MTY0Mzc2fQ.eJdwuwFuJ9y402Oc5tL1qjFa1oKMiLAp1tACbOfxtMA"


### Like or Unlike Post
curl -X POST http://localhost:5000/api/posts/like/681ab6b8264258bc8a9ac9ed \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWE5YTRjMTUyN2RkZDQzNDE2NTBjNSIsImlhdCI6MTc0NjY2ODM5NCwiZXhwIjoxNzQ5MjYwMzk0fQ.pW-6a33PE5Y3wdFJ7YOuQozMJfEu4xMK6CRrFKN07ow"

### Comment on Post
curl -X POST http://localhost:5000/api/posts/comment/681ab6b8264258bc8a9ac9ed \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWE5NDU4OGIzMmRjYWZlNDM2YzRhNSIsImlhdCI6MTc0NjU3MjM3NiwiZXhwIjoxNzQ5MTY0Mzc2fQ.eJdwuwFuJ9y402Oc5tL1qjFa1oKMiLAp1tACbOfxtMA"
-H "Content-Type: application/json" \
-d '{
  "text": "This is a great article!"
}'

### Get Comment by ID
curl -X GET http://localhost:5000/api/comments/681c202c21ca545077cb87f5 \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWE5NDU4OGIzMmRjYWZlNDM2YzRhNSIsImlhdCI6MTc0NjU3MjM3NiwiZXhwIjoxNzQ5MTY0Mzc2fQ.eJdwuwFuJ9y402Oc5tL1qjFa1oKMiLAp1tACbOfxtMA"

### Update Comment (Own or Admin)
curl -X PUT http://localhost:5000/api/comments/681a9dc21527ddd4341650db \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWE5NDU4OGIzMmRjYWZlNDM2YzRhNSIsImlhdCI6MTc0NjU3MjM3NiwiZXhwIjoxNzQ5MTY0Mzc2fQ.eJdwuwFuJ9y402Oc5tL1qjFa1oKMiLAp1tACbOfxtMA" \
-H "Content-Type: application/json" \
-d '{
  "text": "This is an updated comment."
}'

### Delete Comment (Own or Admin)
curl -X DELETE http://localhost:5000/api/comments/681a9dc21527ddd4341650db \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWE5NDU4OGIzMmRjYWZlNDM2YzRhNSIsImlhdCI6MTc0NjU3MjM3NiwiZXhwIjoxNzQ5MTY0Mzc2fQ.eJdwuwFuJ9y402Oc5tL1qjFa1oKMiLAp1tACbOfxtMA"

### Get All Users
curl -X GET http://localhost:5000/api/admin/users \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWE5NDU4OGIzMmRjYWZlNDM2YzRhNSIsImlhdCI6MTc0NjU3MjM3NiwiZXhwIjoxNzQ5MTY0Mzc2fQ.eJdwuwFuJ9y402Oc5tL1qjFa1oKMiLAp1tACbOfxtMA"

### Get All Posts
curl -X GET http://localhost:5000/api/admin/posts \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWE5NDU4OGIzMmRjYWZlNDM2YzRhNSIsImlhdCI6MTc0NjU3MjM3NiwiZXhwIjoxNzQ5MTY0Mzc2fQ.eJdwuwFuJ9y402Oc5tL1qjFa1oKMiLAp1tACbOfxtMA"

### Delete Any Post
curl -X DELETE http://localhost:5000/api/admin/posts/681ac050cb81ba362038432e \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWE5NDU4OGIzMmRjYWZlNDM2YzRhNSIsImlhdCI6MTc0NjU3MjM3NiwiZXhwIjoxNzQ5MTY0Mzc2fQ.eJdwuwFuJ9y402Oc5tL1qjFa1oKMiLAp1tACbOfxtMA"

### Ban Any User
curl -X POST http://localhost:5000/api/admin/ban-user/681a9a4c1527ddd4341650c5 \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWE5NDU4OGIzMmRjYWZlNDM2YzRhNSIsImlhdCI6MTc0NjU3MjM3NiwiZXhwIjoxNzQ5MTY0Mzc2fQ.eJdwuwFuJ9y402Oc5tL1qjFa1oKMiLAp1tACbOfxtMA" \


### 🖼️ Upload Image When Creating Post
curl -X POST http://localhost:5000/api/posts \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWE5NDU4OGIzMmRjYWZlNDM2YzRhNSIsImlhdCI6MTc0NjU3MjM3NiwiZXhwIjoxNzQ5MTY0Mzc2fQ.eJdwuwFuJ9y402Oc5tL1qjFa1oKMiLAp1tACbOfxtMA" \
-F "title=My New Post" \
-F "content=This is my first blog post with an image." \
-F "tags=vue,nodejs,blog" \
-F "image=@C:/Users/Simeon/OneDrive/Pictures/q.png"

